version: "3"

networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: true
    external: false

services:
  phpfpm:
    image: itkdev/php7.2-fpm:alpine
    restart: unless-stopped
    networks:
      - app
    environment:
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MEMORY_LIMIT=128M
    depends_on:
      - memcached
    volumes:
      - .:/app:delegated
      - drush-cache:/root/.drush

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    networks:
      - app
      - frontend
    depends_on:
      - phpfpm
    ports:
      - '80'
    volumes:
      - ${PWD}/.docker/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/app:rw
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_SERVER_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
      #- "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=ITKBasicAuth@file"

  memcached:
    image: 'memcached:latest'
    restart: unless-stopped
    networks:
      - app
    ports:
      - '11211'
    environment:
      - MEMCACHED_CACHE_SIZE=64

  drush:
    image: itkdev/drush6:latest
    networks:
      - app
    entrypoint:
      - drush
    volumes:
      - drush-cache:/root/.drush
      - ./:/app

# Drush cache volume to persist cache between runs.
volumes:
  drush-cache:
